### PR TITLE
Collection of many fixes

### LINKED ISSUE #16: Wrong ARPACK error messages
Originally from https://github.com/JuliaLang/julia/issues/24292

As pointed out in https://github.com/JuliaLang/julia/pull/24192#discussion_r146352634, the error messages in the show method for ARPACKException are not always correct. There are two kinds of ARPACK subroutines (eupd and aupd) that use the same error codes for completely different errors. Right now, the error messages from eupd are used for all exceptions.

Previously, it has been discussed that ARPACK throws more than it should since it is sometimes useful to have access to the intermediate output in cases where we throw, e.g. when the maximum number of iterations has been reached. Hence, this issue could also be fixed as part of a more general adjustment of the error handling in our ARPACK wrappers.

### PR DESCRIPTION
**Pull request by ViralBShah**
Update arpack-ng dependency to 3.8
Replace ARPACKException with AUPD and EUPD exceptions
Use Logging.jl for reporting the errors
Use correct fortran calling convention
Fix #16, #76, #112

### CODE REVIEW

File: src/libarpack.jl [hunk 1]
```diff
@@ -73,26 +89,27 @@ function aupd_wrapper(T, matvecA!::Function, matvecB::Function, solveSI::Functio
...
         if info[] != 0
-            throw(ARPACKException(info[]))
+            throw(XYAUPD_Exception(info[]))
         end
 
         x = view(workd, ipntr[1] .+ zernm1)
         y = view(workd, ipntr[2] .+ zernm1)
         if mode == 1  # corresponds to dsdrv1, dndrv1 or zndrv1
-            if ido[] == 1
+            if ido[] == -1 || ido[] == 1
```
Comment (ViralBShah) [inline src/libarpack.jl:98]: This fixes #76 

cc @andreasnoack

Comment (andreasnoack) [reply src/libarpack.jl:98]: That was never the real issue there. It was just how it surfaced. See https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/118
